### ISSUE TITLE
Analyzing dependencies [!] Unable to find a specification for `ReactorKit`

### ISSUE THREAD

**Issue by trilliwon** [devxoul/ReactorKit#4]
CleverKit pod install 하려고 하니 에러가 납니다 
Analyzing dependencies [!] Unable to find a specification for `ReactorKit`

**Comment by devxoul** [comment]
It's because your local pod spec repository is not up-to-date. Do as following:

```console
$ pod repo update  # update local pod spec repo
$ pod install
```

**Comment by trilliwon** [comment]
오, 감사합니다
