### ISSUE TITLE
Why differentiate between actions and mutations? 

### ISSUE THREAD

**Issue by seivan** [devxoul/ReactorKit#5]
I understand that mutations are the effect of side effects, but aren't they essentially the same thing in the examples? 

It reminds me a little bit of https://redux-observable.js.org/docs/basics/Epics.html (which is nice!) but they don't differentiate between actions in epics (what you call mutations).
Instead they wrap their **async** actions in an observable

It could just be three actions: 

```swift
enum Action {
    case refreshFollowingStatus(Int) //async
    case follow(Int) //async
    case followed(Bool)
  }
  ```

**Comment by seivan** [comment]
Ah, I see now. 
https://github.com/devxoul/ReactorKit/blob/master/Sources/Reactor.swift#L17

**Comment by devxoul** [comment]
Just do not define Mutation then the Mutation will be treated as same as Action :)
